services:
  postgres_db:
    container_name: task_app_db
    image: postgres:17
    restart: always


  backend:
    build: ./backend
    container_name: task_app_backend
    restart: always
    depends_on:
      - postgres_db

  frontend:
    build: ./frontend
    container_name: task_app_frontend
    restart: always
    depends_on:
      - backend

